name: dcf_calculator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.0.1
  - werkzeug=2.0.3
  - numpy=1.21.0
  - pandas=1.3.0
  - yfinance=0.2.28
  - pip=21.1.3
  - pip:
    - requests==2.31.0